# admin/config.yml

backend:
  name: github
  repo: cepoide/cepoide.github.io  # Tu usuario y repositorio
  branch: main                    # O 'master' si usas esa como rama principal
  
  # --- LÍNEAS NUEVAS Y CRUCIALES ---
  auth_type: implicit             # Le decimos que use el método de autenticación del navegador
  app_id: TU_CLIENT_ID_DE_GITHUB  # Le decimos que use TU aplicación de GitHub

media_folder: "img"
public_folder: "/img"

collections:
  - name: "proyectos"
    label: "Proyectos"
    label_singular: "Proyecto"
    file: "proyectos.json"
    widget: "list"
    add_to_top: true
    fields:
      - {label: "Título", name: "titulo", widget: "string"}
      - {label: "Descripción", name: "descripcion", widget: "markdown"}
      - {label: "URL de la Imagen", name: "imagenUrl", widget: "image"}
      - {label: "Texto Alternativo (Alt)", name: "altImagen", widget: "string", optional: true}
      - {label: "URL del Proyecto", name: "enlaceUrl", widget: "string"}
      - {label: "Categoría", name: "categoria", widget: "select", options: ["Facultad", "Personal"]}
