# === VERSIÓN FINAL CON CODIFICACIÓN CORRECTA ===

backend:
  name: github
  repo: cepoide/cepoide.github.io
  branch: main
  auth_type: implicit
  app_id: Ov23liw9dOe4vGZ3Ueqy # Asegúrate de que este es tu Client ID

media_folder: "img"
public_folder: "/img"

collections:
  - name: "proyectos"
    label: "Proyectos"
    files:
      - name: "lista_proyectos"
        label: "Lista de Proyectos"
        file: "proyectos.json"
        create: true
        fields:
          - {label: "Título", name: "titulo", widget: "string"}
          - {label: "Descripción", name: "descripcion", widget: "markdown"}
          - {label: "URL de la Imagen", name: "imagenUrl", widget: "image"}
          - {label: "Texto Alternativo (Alt)", name: "altImagen", widget: "string", optional: true}
          - {label: "URL del Proyecto", name: "enlaceUrl", widget: "string"}
          - {label: "Categoría", name: "categoria", widget: "select", options: ["Facultad", "Personal"]}